# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArrivalTimeCalculator
                                 A QGIS plugin
 A plugin for calculating the arrival time of a fire truck between two points based on distance and speed
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-16
        copyright            : (C) 2024 by SPAA
        email                : morozov.v_ob-122bt@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'SPAA'
__date__ = '2024-12-16'
__copyright__ = '(C) 2024 by SPAA'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ArrivalTimeCalculator class from file ArrivalTimeCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Arrival_Time_Calculator import ArrivalTimeCalculator
    return ArrivalTimeCalculator(iface)
